## src/main/BUILD

cc_binary(
    name = "cpp_app",
    srcs = ["main.cpp"],
    deps = [
        
        "//src/Book:Book",
        "//src/AuthorList:AuthorList",
        "//src/Author:Author",
        "//src/Library:Library",
    ],
)
