
cc_library(
    name = "FirstSessionStudent",
    srcs = ["FirstSessionStudent.cpp"],
    hdrs = ["FirstSessionStudent.h"],
    deps = ["//src/Student:Student"],
    visibility = ["//visibility:public"]
)
