
cc_test(
    name = "tests",
    srcs = ["tests.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Tree:Tree",
        "//src/ForestTree:ForestTree",
        "//src/FruitTree:FruitTree",
        "//src/TreeContainer:TreeContainer"
    ]
)
