
cc_library(
    name = "SecondSessionStudent",
    srcs = ["SecondSessionStudent.cpp"],
    hdrs = ["SecondSessionStudent.h"],
    deps = [
        "//src/Student:Student",
        "//src/FirstSessionStudent:FirstSessionStudent"],
    visibility = ["//visibility:public"]
)
