
cc_test(
    name = "tests",
    srcs = ["tests.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Person:Person",
        "//src/Professor:Professor",
        "//src/Student:Student"
    ]
)
