## src/tests/functionsTests/BUILD

cc_library(
    name = "functionsTests",
    srcs = ["functionsTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/functions:functions",
    ]
)
