
cc_library(
    name = "TreeContainer",
    srcs = ["TreeContainer.cpp"],
    hdrs = ["TreeContainer.h"],
    deps = [
        "//src/Tree:Tree",
        "//src/ForestTree:ForestTree",
        "//src/FruitTree:FruitTree"],
    visibility = ["//visibility:public"]
)
