
cc_test(
    name = "tests",
    srcs = ["tests.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Student:Student",
        "//src/FirstSessionStudent:FirstSessionStudent",
        "//src/SecondSessionStudent:SecondSessionStudent"
    ]
)
